# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wZ9iknYBoRtpSU8iRf-cdtnZA8wTzhA8
"""

from google.colab import files
files.upload()

import pandas as pd
data = pd.read_csv("Smarket.csv")   # https://github.com/anirbanrkmission/stock_market_analysis

per_week_lag = []

for i in range(0,len(data['Today']),7):
  per_week_lag.append(data['Today'][i:i+7].sum())

import matplotlib.pyplot as plt
plt.figure()
plt.plot(per_week_lag)
#plt.figure()
#plt.plot(per_month_lag)
plt.show()

pos_week_no=0;neg_week_no=0;pos_week_val=0;neg_week_val =0
for i in range(len(per_week_lag)):
  if per_week_lag[i] > 0:
    pos_week_no += 1 
    pos_week_val += per_week_lag[i]
  elif per_week_lag[i]<0:
    neg_week_no += 1
    neg_week_val -= per_week_lag[i]

print(pos_week_no,'\n',neg_week_no,'\n',pos_week_val,'\n',neg_week_val)

avg_pos = pos_week_val/pos_week_no; avg_neg = neg_week_val/neg_week_no

print(avg_pos,'\n',avg_neg)







data_up = data[data['Direction']=='Up']
data_down = data[data['Direction']=='Down']
print(len(data_up))
print(len(data_down))

len(data['Today'])





data_01 = data[data['Year']==2001]
data_01_up = data_01[data_01['Direction']=='Up']
data_01_down = data_01[data_01['Direction']=='Down']

import matplotlib.pyplot as plt
plt.plot(data_01_up['Volume'],'red')
plt.plot(data_01_up['Today'],'--b')
#plt.grid()

